const vehicles = [
  {
    name: 'N/A',
    vehicle_name: 'none',
    status: 'Offline',
    vehicle_plateno: 'anh-001',
    longitude: '67.1236532',
    latitude: '24.917881350000002',
    driverapproved: '-',
    current_location: null,
    cargo: 30000,
    speed: 0,
    end_location: 'NIC'
  },
  {
    name: 'N/A',
    vehicle_name: 'Corolla',
    status: 'Offline',
    vehicle_plateno: 'AQT-018',
    longitude: '67.1236077',
    latitude: '24.91793725',
    driverapproved: '-',
    current_location: 'Gulistan e Johar Block 15',
    cargo: 250000,
    speed: 0,
    end_location: 'Karachi'
  },
  {
    name: 'Syed Saad Farooq',
    vehicle_name: 'Toyota Corolla',
    status: 'Offline',
    vehicle_plateno: 'ALA-548',
    longitude: '67.11667033333333',
    latitude: '24.930301166666666',
    driverapproved: '-',
    current_location: 'یونیورسٹی روڈ',
    cargo: 1000,
    speed: 0,
    end_location: 'ByteCorp'
  },
  {
    name: 'N/A',
    vehicle_name: 'EK-Wagon',
    status: 'Offline',
    vehicle_plateno: 'BHT-074',
    longitude: '67.1236532',
    latitude: '24.917881350000002',
    driverapproved: '-',
    current_location: 'Gulistan e Johar Block 15',
    cargo: 500000,
    speed: 0,
    end_location: 'Islamabad'
  },
  {
    name: 'N/A',
    vehicle_name: 'Honda Civic',
    status: 'Offline',
    vehicle_plateno: 'NEH-000',
    longitude: null,
    latitude: null,
    driverapproved: '-',
    current_location: null,
    cargo: 30000,
    speed: 0,
    end_location: 'NIC'
  },
  {
    name: 'N/A',
    vehicle_name: 'Honda Civic',
    status: 'Offline',
    vehicle_plateno: 'AJF-832',
    longitude: null,
    latitude: null,
    driverapproved: '-',
    current_location: null,
    cargo: 30000,
    speed: 0,
    end_location: 'NIC'
  },
  {
    name: 'N/A',
    vehicle_name: 'Honda Civic',
    status: 'Offline',
    vehicle_plateno: 'SON-123',
    longitude: '67.1129638',
    latitude: '24.9295937',
    driverapproved: '-',
    current_location: 'یونیورسٹی روڈ',
    cargo: 30000,
    speed: 0,
    end_location: 'NIC'
  },
  {
    name: 'N/A',
    vehicle_name: 'Honda Civic',
    status: 'Offline',
    vehicle_plateno: 'BKL-123',
    longitude: null,
    latitude: null,
    driverapproved: '-',
    current_location: null,
    cargo: 30000,
    speed: 0,
    end_location: 'NIC'
  },
  {
    name: 'N/A',
    vehicle_name: 'Honda Fit',
    status: 'Offline',
    vehicle_plateno: 'BKT-642',
    longitude: '67.0628255',
    latitude: '24.9459015',
    driverapproved: '-',
    current_location: 'B 203 North Nazimabad Block M',
    cargo: 1000,
    speed: 0,
    end_location: 'ByteCorp'
  },
  {
    name: 'N/A',
    vehicle_name: 'Honda-City',
    status: 'Offline',
    vehicle_plateno: 'BAP-925',
    longitude: '67.0627784',
    latitude: '24.945847816666667',
    driverapproved: '-',
    current_location: 'B 203',
    cargo: 1000,
    speed: 0,
    end_location: 'ByteCorp'
  },
  {
    name: 'N/A',
    vehicle_name: 'HONDA',
    status: 'Offline',
    vehicle_plateno: 'ABC-123',
    longitude: '67.06274133333334',
    latitude: '24.945986833333333',
    driverapproved: '-',
    current_location: 'شمالی ناظم آباد North Nazimabad Town',
    cargo: 888,
    speed: 0,
    end_location: 'KHI'
  }
];

export default vehicles;
